# Generated by Django 5.1.1 on 2024-12-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='qr_code',
        ),
    ]
