# Generated by Django 5.1.1 on 2024-12-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.CharField(default='', max_length=100),
        ),
    ]
