# Generated by Django 5.1.1 on 2024-12-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_notification_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
