# Generated by Django 5.1.1 on 2024-12-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cccdcard',
            name='personal_identifi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
