# Generated by Django 5.1.1 on 2024-10-22 08:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CCCDCard',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('dateOfBirth', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('placeOfOrigin', models.CharField(max_length=255)),
                ('placeOfResidence', models.CharField(max_length=255)),
                ('dateOfExpiry', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cccdCards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
